# Generated by Django 5.0.6 on 2026-09-28 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('start_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('random_questions', models.BooleanField(default=False)),
                ('random_options', models.BooleanField(default=False)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0.25, max_digits=4)),
                ('show_result', models.BooleanField(default=True)),
                ('show_answers', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('require_fullscreen', models.BooleanField(default=True)),
                ('tab_warning_limit', models.PositiveIntegerField(default=3)),
                ('prevent_copy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='curriculum.courseweek')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mappings', to='questions.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('quiz', 'question')},
            },
        ),
    ]
